import type { Metadata } from "next";
import { karlaSans } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${karlaSans.className} flex justify-center items-center px-4 py-8 sm:px-10 antialiased bg-[hsl(var(--green-200))]`}
            >
                {children}
            </body>
        </html>
    );
}
